#title in header
title: "Keep Simple"

#main info
#owner
# owner: "I am Adi Sakti Jrs"
# email: test@test.test
# info: "A student and web developer from Indonesia ğŸ‡®ğŸ‡©"
#description
# desc: "This is Minima, an undoubtedly simple and lightweight dark/light mode theme for Hexo. I created this from scratch using Skeleton CSS boilerplate. It only uses CSS and Vanilla JS, without using unnecessary third-party 'render-blocking' libraries! ğŸ˜"

#menu
menu:
  About: /About

#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/shinymimiq
twitter: https://twitter.com/shinymimiq
instagram: https://instagram.com/shinymimiq

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
# disqus_shortname: https-adisaktijrs-github-io
